all: 
	g++ carraghan-pardalos.cpp -o carraghan-pardalos.cpp.bin; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_1.mtx -o outputs/input_1.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_2.mtx -o outputs/input_2.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_3.mtx -o outputs/input_3.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_4.mtx -o outputs/input_4.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_5.mtx -o outputs/input_5.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_6.mtx -o outputs/input_6.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_7.mtx -o outputs/input_7.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_8.mtx -o outputs/input_8.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_9.mtx -o outputs/input_9.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_10.mtx -o outputs/input_10.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_11.mtx -o outputs/input_11.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_12.mtx -o outputs/input_12.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_13.mtx -o outputs/input_13.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_14.mtx -o outputs/input_14.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_15.mtx -o outputs/input_15.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_16.mtx -o outputs/input_16.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_17.mtx -o outputs/input_17.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_18.mtx -o outputs/input_18.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_19.mtx -o outputs/input_19.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_20.mtx -o outputs/input_20.out; echo ""
	rm carraghan-pardalos.cpp.bin

build: 
	g++ carraghan-pardalos.cpp -o carraghan-pardalos.cpp.bin
	
clean: 
	rm carraghan-pardalos.cpp.bin

run:
	./carraghan-pardalos.cpp.bin -f inputs/input_1.mtx -o outputs/input_1.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_2.mtx -o outputs/input_2.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_3.mtx -o outputs/input_3.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_4.mtx -o outputs/input_4.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_5.mtx -o outputs/input_5.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_6.mtx -o outputs/input_6.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_7.mtx -o outputs/input_7.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_8.mtx -o outputs/input_8.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_9.mtx -o outputs/input_9.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_10.mtx -o outputs/input_10.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_11.mtx -o outputs/input_11.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_12.mtx -o outputs/input_12.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_13.mtx -o outputs/input_13.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_14.mtx -o outputs/input_14.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_15.mtx -o outputs/input_15.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_16.mtx -o outputs/input_16.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_17.mtx -o outputs/input_17.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_18.mtx -o outputs/input_18.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_19.mtx -o outputs/input_19.out; echo ""
	./carraghan-pardalos.cpp.bin -f inputs/input_20.mtx -o outputs/input_20.out; echo ""
	
