all:
	g++ -o kosaraju.bin kosaraju.cpp
	mv kosaraju.bin ../Bat1
	cd ../Bat1 && ./Bat1.sh && rm kosaraju.bin

ignore:
	g++ -o kosaraju.bin ignore.cpp
	mv kosaraju.bin ../Bat1
	cd ../Bat1 && ./Bat1.sh

ignore2:
	g++ -o kosaraju.bin ignore2.cpp
	mv kosaraju.bin ../Bat1
	cd ../Bat1 && ./Bat1.sh

testelocal:
	g++ -o kosaraju.bin kosaraju.cpp
	./kosaraju.bin -f entrada.in
	
testelocal2:
	g++ -o kosaraju.bin kosaraju.cpp